#!/usr/bin/env bash
#
# config/rwahs/components/configuration - Configuration component configuration for integration script.
#

set -e
set -u

repo='rwahs/providence-configuration'
repoDefaultTargetCommitish='master'
targetParent='local/providence-configuration'
