#!/usr/bin/env bash
#
# config/rwahs/components/importer - Importer component configuration for integration script.
#

set -e
set -u

repo='rwahs/import-scripts'
repoDefaultTargetCommitish='master'
targetParent='import-scripts'


function postDeploy {
    targetRoot="${1}"
    localSettingsRoot="${2}"

    ln -s "${localSettingsRoot}/source" "${targetRoot}/${targetParent}/current/importScripts/source"
}
