#!/usr/bin/env bash
#
# config/rwahs/components/importer - Importer component configuration for integration script.
#

set -e
set -u

repo='rwahs/import-scripts'
repoDefaultTargetCommitish='master'
targetParent='local/import-scripts'
