#!/usr/bin/env bash
#
# config/rwahs/components/profile - Profile component configuration for integration script.
#

set -e
set -u

repo='rwahs/installation-profile'
repoDefaultTargetCommitish='master'
targetParent='installation-profile'
