#!/usr/bin/env bash
#
# config/rwahs/components/providence - Providence component configuration for integration script.
#

set -e
set -u

repo='rwahs/providence'
repoDefaultTargetCommitish='master-fix'
targetParent='web/providence'

function postDeploy {
    sudo service apache2 restart
    sudo service php5-fpm restart
}
