#!/usr/bin/env bash
#
# config/rwahs/components/providence - Providence component configuration for integration script.
#

set -e
set -u

repo='rwahs/providence'
repoDefaultTargetCommitish='master-fix'
targetParent='providence'

function preDeploy {
    if [ ! -v COLLECTIVEACCESS_HOME ]; then
        echo "Error: The COLLECTIVEACCESS_HOME environment variable is required to deploy the 'providence' component" >&2
        exit 1
    elif [ ! -f "${COLLECTIVEACCESS_HOME}/support/bin/caUtils" ]; then
        echo "Error: The COLLECTIVEACCESS_HOME environment variable does not point to a valid providence installation" >&2
        exit 1
    fi

    sudo service apache2 stop
    sudo service php5-fpm stop
}

function postDeploy {
    targetRoot="${1}"
    localSettingsRoot="${2}"

    ln -s "${localSettingsRoot}/setup.php" "${targetRoot}/${targetParent}/current/setup.php"
    ln -s "${localSettingsRoot}/../storage/media/collectiveaccess" "${targetRoot}/${targetParent}/current/media/collectiveaccess"
    rm -rf "${targetRoot}/import"
    ln -s "${localSettingsRoot}/../storage/import" "${targetRoot}/${targetParent}/current/import"

    yes | "${COLLECTIVEACCESS_HOME}/support/bin/caUtils" update-database-schema

    sudo service apache2 start
    sudo service php5-fpm start
}
