#!/usr/bin/env bash
#
# config/rwahs/components/tools - Tools component configuration for integration script.
#

set -e
set -u

repo='rwahs/tools'
repoDefaultTargetCommitish='master'
targetParent='tools'
