#!/usr/bin/env bash
#
# rwahs/help - Support functions for help text in integration script
#

# Show task-specific usage instructions
function showTaskHelp {
    local helpTask="${1}"
    if ! inArray tasks "${helpTask}"; then
        echo "Requested help for unknown task '${helpTask}'; valid tasks are: ${tasks[@]}"
    else
        ${helpTask}_showHelp
    fi
}

# Show general usage instructions
function showHelp {
    echo "COMMAND DESCRIPTION:"
    echo "    Run a specified task with options"
    echo
    echo "USAGE:"
    echo "    ${0} <task> [-e <environment>] [-c <component>...]"
    echo
    echo "WHERE:"
    echo "    <task> is the name of a task to perform: help ${tasks[@]}"
    echo "    -e <environment> gives the name of the environment to control remotely: ${environments[@]}"
    echo "    -c <component> gives the name of the component to process: ${components[@]}"
    echo
    echo "NOTES:"
    echo "    1. If the -e option is omitted, the script will run locally"
    echo "    2. Not all tasks require or use the -e or -c options, however they are required for other tasks"
    echo "    3. Some tasks have additional options"
    echo
    echo "For more information on specific tasks, run ${0} help <task>"
    echo
    return 0
}
