#!/usr/bin/env bash
#
# config/rwahs/env/staging - Staging environment configuration for integration script.
#

set -e
set -u

host='staging-collections.histwest.org.au'
user='ca'
targetRoot='/data/deploy'
localSettingsRoot='/data/local'
localStorageRoot='/data/storage'
adminEmailAddress='rwahs@gaiaresources.com.au'
