#!/usr/bin/env bash
#
# config/rwahs/env/staging - Staging environment configuration for integration script.
#

set -e
set -u

host='52.62.226.104'
user='ca'
targetRoot='/data'
adminEmailAddress='rwahs@gaiaresources.com.au'
