#!/usr/bin/env bash
#
# config/rwahs/env/uat - UAT environment configuration for integration script.
#

set -e
set -u

host='52.63.20.116'
user='ca'
targetRoot='/data/deploy'
adminEmailAddress='rwahs@gaiaresources.com.au'
