#!/usr/bin/env bash
#
# rwahs/tasks/deploy - Function definitions for "deploy" task.
#

set -e
set -u

function deploy_showHelp {
    echo "TASK DESCRIPTION:"
    echo "    Transfer the specified release to the specified environment and update the environment to make the"
    echo "    specified release the 'current' version used in the given environment."
    echo
}

function deploy_runTask {
    echo "Running 'deploy' task..."
}
