#!/usr/bin/env bash
#
# rwahs/tasks/import - Function definitions for "import" task.
#

set -e
set -u

function import_showHelp {
    local programName toolsDir

    # Function arguments
    programName="${1}"
    toolsDir="${2}"
    shift 2

    echo
    echo "Run the import scripts, converting data from the legacy database format into the format required by"
    echo "CollectiveAccess, and inserting the data into the environment's database."
    echo
    echo "USAGE:"
    echo "    ${programName} build -e <environment> [-n]"
    echo
    echo "WHERE:"
    echo "    -e <environment> gives the name of the environment to import data into."
    echo "         Valid values: $(ls -m "${toolsDir}/config/${programName}/env")"
    echo "    -n indicates that the database should be cleared before importing (equivalent to running"
    echo "         \`${programName} nuke\` prior to importing)"
    echo
}

function import_runTask {
    local programName toolsDir

    # Function arguments
    programName="${1}"
    toolsDir="${2}"
    shift 2

    echo "Running 'import' task..."
}
